### ISSUE TITLE
build-folder option not working

### ISSUE THREAD

**Issue by mrexodia** [AshampooSystems/boden#19] opened 2019-08-19 19:27 UTC
It looks like something is broken with the `--build-folder` option.

```
$ ./boden prepare --build-folder ./build2
[2019-08-19 21:24:57,146] Defaulting to: ios - Xcode
[2019-08-19 21:24:57,146] Build system does not match the one used when the projects for this platform were first prepared. Cleaning existing build files.
[2019-08-19 21:24:57,160] Preparing ./build2/ios/std/Xcode
[2019-08-19 21:24:57,189] Configuring ...
-- The C compiler identification is unknown
-- CMake Error: Could not find cmake module file: ./build2/ios/std/Xcode/CMakeFiles/3.12.3/CMakeCCompiler.cmake
-- The CXX compiler identification is unknown
-- CMake Error: Could not find cmake module file: ./build2/ios/std/Xcode/CMakeFiles/3.12.3/CMakeCXXCompiler.cmake
-- CMake Error at CMakeLists.txt:14 (project):
  No CMAKE_C_COMPILER could be found.



-- CMake Error at CMakeLists.txt:14 (project):
  No CMAKE_CXX_COMPILER could be found.



-- Configuring incomplete, errors occurred!
See also "./build2/ios/std/Xcode/CMakeFiles/CMakeOutput.log".
See also "./build2/ios/std/Xcode/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "/Users/duncan/Projects/boden_build/./bauer/bauer.py", line 71, in main
    return run(argv)
  File "/Users/duncan/Projects/boden_build/./bauer/bauer.py", line 67, in run
    commandProcessor.process()
  File "/Users/duncan/Projects/boden_build/./bauer/commandprocessor.py", line 91, in process
    self.prepare(configuration, platformState);
  File "/Users/duncan/Projects/boden_build/./bauer/commandprocessor.py", line 135, in prepare
    self.buildExecutor.prepare(platformState, configuration, self.args)
  File "/Users/duncan/Projects/boden_build/./bauer/buildexecutor.py", line 155, in prepare
    self.cmake.configure(cmakeArguments)
  File "/Users/duncan/Projects/boden_build/./bauer/cmake.py", line 92, in configure
    self.waitForResult("configure", "CONFIGURE")
  File "/Users/duncan/Projects/boden_build/./bauer/cmake.py", line 83, in waitForResult
    raise Exception("Error occured during configure:", payload["errorMessage"])
Exception: ('Error occured during configure:', 'Configuration failed.')
```

Any ideas?

Doing `./boden prepare --build-folder $(pwd)/build2` seems to work fine for some reason.

**Comment by Maddimax** [comment] 2019-08-20 06:27
I cannot reproduce the issue, but the detection code is not the best. Could you:
1) Run ./boden with "-d"
2) Try to delete / move the "build2" folder and run the command again.

Does $(pwd) contain any symbolic links?

**Comment by mrexodia** [comment] 2019-08-20 07:20
This was on a clean clone, no symlinks. I do have a case sensitive filesystem though.

**Comment by Maddimax** [comment] 2019-08-21 07:12
I tried to reproduce on a case sensitive filesystem as well but did not run into issues. Can you send me the output with "-d" added ?

**Comment by mrexodia** [comment] 2019-08-21 08:16
```
$ ./boden -d prepare --build-folder ./build2
[2019-08-21 10:16:06,710](bauerargparser): Bauer options: Namespace(accept_terms=False, arch=None, build_folder='./build2', build_system=None, cmake_option=None, command='prepare', config=None, debug=False, macos_min_version=None, macos_sdk_path=None, package_folder=None, package_generator=None, platform=None, target=None)
[2019-08-21 10:16:06,711](cmake): CMake found at: /usr/local/bin/cmake
[2019-08-21 10:16:06,711](cmake): CMake found at: /usr/local/bin/cmake
[2019-08-21 10:16:06,711](commandprocessor): Starting command: prepare
[2019-08-21 10:16:06,711](buildfolder): Existing configurations:
[2019-08-21 10:16:06,711](commandprocessor): Selected platform list:
[2019-08-21 10:16:06,711](commandprocessor): Defaulting to: ios - Xcode
[2019-08-21 10:16:06,712](commandprocessor): Build system does not match the one used when the projects for this platform were first prepared. Cleaning existing build files.
[2019-08-21 10:16:06,712](commandprocessor): (No previous state found)
[2019-08-21 10:16:06,712](commandprocessor): New config: BuildConfiguration(platform='ios', arch='std', buildsystem='Xcode', config=None)
[2019-08-21 10:16:06,715](commandprocessor): Preparing ./build2/ios/std/Xcode
[2019-08-21 10:16:06,715](buildexecutor): prepare(BuildConfiguration(platform='ios', arch='std', buildsystem='Xcode', config=None))
[2019-08-21 10:16:06,728](cmake): Server Protocol version: [1, 2]
[2019-08-21 10:16:06,732](cmake): VERSION: 3.12.3
[2019-08-21 10:16:06,732](buildexecutor): Starting configure ...
[2019-08-21 10:16:06,732](buildexecutor):  Source Directory: /Users/duncan/Projects/boden
[2019-08-21 10:16:06,732](buildexecutor):  Output Directory: ./build2/ios/std/Xcode
[2019-08-21 10:16:06,732](buildexecutor):  Arguments: ['-DCMAKE_TOOLCHAIN_FILE=/Users/duncan/Projects/boden/cmake/toolchains/ios.xcode.toolchain.cmake', '-A std']
[2019-08-21 10:16:06,733](buildexecutor):  Generator: Xcode
[2019-08-21 10:16:06,733](cmake): Configuring ...
-- The C compiler identification is unknown
-- CMake Error: Could not find cmake module file: ./build2/ios/std/Xcode/CMakeFiles/3.12.3/CMakeCCompiler.cmake
-- The CXX compiler identification is unknown
-- CMake Error: Could not find cmake module file: ./build2/ios/std/Xcode/CMakeFiles/3.12.3/CMakeCXXCompiler.cmake
-- CMake Error at CMakeLists.txt:14 (project):
  No CMAKE_C_COMPILER could be found.



-- CMake Error at CMakeLists.txt:14 (project):
  No CMAKE_CXX_COMPILER could be found.



-- Configuring incomplete, errors occurred!
See also "./build2/ios/std/Xcode/CMakeFiles/CMakeOutput.log".
See also "./build2/ios/std/Xcode/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "/Users/duncan/Projects/boden/./bauer/bauer.py", line 71, in main
    return run(argv)
  File "/Users/duncan/Projects/boden/./bauer/bauer.py", line 67, in run
    commandProcessor.process()
  File "/Users/duncan/Projects/boden/./bauer/commandprocessor.py", line 91, in process
    self.prepare(configuration, platformState);
  File "/Users/duncan/Projects/boden/./bauer/commandprocessor.py", line 135, in prepare
    self.buildExecutor.prepare(platformState, configuration, self.args)
  File "/Users/duncan/Projects/boden/./bauer/buildexecutor.py", line 155, in prepare
    self.cmake.configure(cmakeArguments)
  File "/Users/duncan/Projects/boden/./bauer/cmake.py", line 92, in configure
    self.waitForResult("configure", "CONFIGURE")
  File "/Users/duncan/Projects/boden/./bauer/cmake.py", line 83, in waitForResult
    raise Exception("Error occured during configure:", payload["errorMessage"])
Exception: ('Error occured during configure:', 'Configuration failed.')
```

**Comment by Maddimax** [comment] 2019-08-21 10:08
Would you replace "boden/bauer/buildexecutor.py" with the version from the attached
[buildexecutor.py.zip](https://github.com/AshampooSystems/boden/files/3524768/buildexecutor.py.zip) and send me the output with -d again?

**Comment by mrexodia** [comment] 2019-08-21 10:26
```
$ ./boden -d prepare --build-folder ./build2
[2019-08-21 12:25:45,416](bauerargparser): Bauer options: Namespace(accept_terms=False, arch=None, build_folder='./build2', build_system=None, cmake_option=None, command='prepare', config=None, debug=False, macos_min_version=None, macos_sdk_path=None, package_folder=None, package_generator=None, platform=None, target=None)
[2019-08-21 12:25:45,417](cmake): CMake found at: /usr/local/bin/cmake
[2019-08-21 12:25:45,417](cmake): CMake found at: /usr/local/bin/cmake
[2019-08-21 12:25:45,417](commandprocessor): Starting command: prepare
[2019-08-21 12:25:45,418](buildfolder): Existing configurations:
[2019-08-21 12:25:45,418](commandprocessor): Selected platform list:
[2019-08-21 12:25:45,418](commandprocessor): Defaulting to: ios - Xcode
[2019-08-21 12:25:45,418](commandprocessor): Build system does not match the one used when the projects for this platform were first prepared. Cleaning existing build files.
[2019-08-21 12:25:45,419](commandprocessor): (No previous state found)
[2019-08-21 12:25:45,419](commandprocessor): New config: BuildConfiguration(platform='ios', arch='std', buildsystem='Xcode', config=None)
[2019-08-21 12:25:45,423](commandprocessor): Preparing ./build2/ios/std/Xcode
[2019-08-21 12:25:45,424](buildexecutor): prepare(BuildConfiguration(platform='ios', arch='std', buildsystem='Xcode', config=None))
[2019-08-21 12:25:45,444](buildexecutor): Environment info:
[2019-08-21 12:25:45,445](buildexecutor):       "xcode-select -p": "/Applications/Xcode.app/Contents/Developer"
[2019-08-21 12:25:45,445](buildexecutor):       "which c++": "/usr/bin/c++"
[2019-08-21 12:25:45,461](cmake): Server Protocol version: [1, 2]
[2019-08-21 12:25:45,463](cmake): VERSION: 3.12.3
[2019-08-21 12:25:45,464](buildexecutor): Starting configure ...
[2019-08-21 12:25:45,464](buildexecutor):  Source Directory: /Users/duncan/Projects/boden
[2019-08-21 12:25:45,464](buildexecutor):  Output Directory: ./build2/ios/std/Xcode
[2019-08-21 12:25:45,464](buildexecutor):  Arguments: ['-DCMAKE_TOOLCHAIN_FILE=/Users/duncan/Projects/boden/cmake/toolchains/ios.xcode.toolchain.cmake', '-A std']
[2019-08-21 12:25:45,464](buildexecutor):  Generator: Xcode
[2019-08-21 12:25:45,464](cmake): Configuring ...
-- The C compiler identification is unknown
-- CMake Error: Could not find cmake module file: ./build2/ios/std/Xcode/CMakeFiles/3.12.3/CMakeCCompiler.cmake
-- The CXX compiler identification is unknown
-- CMake Error: Could not find cmake module file: ./build2/ios/std/Xcode/CMakeFiles/3.12.3/CMakeCXXCompiler.cmake
-- CMake Error at CMakeLists.txt:14 (project):
  No CMAKE_C_COMPILER could be found.



-- CMake Error at CMakeLists.txt:14 (project):
  No CMAKE_CXX_COMPILER could be found.



-- Configuring incomplete, errors occurred!
See also "./build2/ios/std/Xcode/CMakeFiles/CMakeOutput.log".
See also "./build2/ios/std/Xcode/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "/Users/duncan/Projects/boden/./bauer/bauer.py", line 71, in main
    return run(argv)
  File "/Users/duncan/Projects/boden/./bauer/bauer.py", line 67, in run
    commandProcessor.process()
  File "/Users/duncan/Projects/boden/./bauer/commandprocessor.py", line 91, in process
    self.prepare(configuration, platformState);
  File "/Users/duncan/Projects/boden/./bauer/commandprocessor.py", line 135, in prepare
    self.buildExecutor.prepare(platformState, configuration, self.args)
  File "/Users/duncan/Projects/boden/./bauer/buildexecutor.py", line 166, in prepare
    self.cmake.configure(cmakeArguments)
  File "/Users/duncan/Projects/boden/./bauer/cmake.py", line 92, in configure
    self.waitForResult("configure", "CONFIGURE")
  File "/Users/duncan/Projects/boden/./bauer/cmake.py", line 83, in waitForResult
    raise Exception("Error occured during configure:", payload["errorMessage"])
Exception: ('Error occured during configure:', 'Configuration failed.')

```

**Comment by Maddimax** [comment] 2019-08-21 11:19
Is this a newly setup computer? If so, ```sudo xcodebuild -license accept``` might help. 

Does it actually work if you don't specify the --build-folder option ?

**Comment by mrexodia** [comment] 2019-08-21 11:23
No it’s an ancient system, but running the latest osx. I can successfully
build boden etc, just not with a relative path in the build folder.
Absolute path and no path works out of the box.

**Comment by Maddimax** [comment] 2019-08-21 11:29
Ok, I've run out of things to try. As a workaround I've changed the script to always convert the build folder path to absolute ( if you'd like to try: 
[buildfolder.py.zip](https://github.com/AshampooSystems/boden/files/3525086/buildfolder.py.zip) )
I'll add that to the next release.

**Comment by mrexodia** [comment] 2019-08-21 12:05
Yeah that one works great, thanks!

**Comment by Maddimax** [comment] 2019-08-23 07:52
We've merged the fix into master. Thanks for your help investigating!

**Closed by Maddimax** 2019-08-23 07:52 UTC
Labels: bug, question
